{
  metrics = {
    height = 30;
    fontSize = "16.25px";
    borderWidth = "2px";
    buttonRadius = "5px";
    moduleVerticalPadding = "1.25px";
    workspaceVerticalPadding = "5px";
    clockLetterSpacing = "1.25px";
    trayIconSize = 20;
  };

  dark = ''
    @define-color teal #00ffff; @define-color teal-dim #00cccc; @define-color teal-light #00ffd5; @define-color green #00ff9f; @define-color pink #ff33cc; @define-color red #ff0080; @define-color orange #ff4d00; @define-color yellow #ffff00; @define-color purple #bd00ff; @define-color blue #00b8ff; @define-color grey #888888; @define-color gold #ffcc00; @define-color black #000000; @define-color black-gradient #0a0a0a;
    * { font-family: 'JetBrainsMono Nerd Font', 'JetBrains Mono', 'Noto Sans Mono', 'Font Awesome 6 Free', 'Font Awesome 6 Brands', monospace; font-size: 16.25px; font-weight: 500; }
    window#waybar { background: linear-gradient(180deg, @black 0%, @black-gradient 100%); border-bottom: 2px solid @teal; box-shadow: 0 0 25px @teal; color: @teal; transition-property: background-color, border-color, box-shadow; transition-duration: 0.3s; border-radius: 0 0; }
    window#waybar.hidden { opacity: 0.2; } window#waybar.empty { background-color: transparent; } window#waybar.solo { background-color: @black; border: 2px solid @teal; }
    button { border: none; border-radius: 5px; background: rgba(0, 255, 255, 0.1); color: @teal; } button:hover { background: rgba(0, 255, 255, 0.2); box-shadow: 0 0 18.75px @teal; }
    #workspaces button { padding: 5px 8px; margin: 0 4px; background: transparent; color: @teal-dim; border: none; } #workspaces button:hover { color: @teal; } #workspaces button.active { color: #B91C1C; font-weight: bold; } #workspaces button.urgent { color: @pink; } #workspaces button.dragging { opacity: 0.45; } #workspaces button.drop-before { color: @yellow; background: rgba(255, 255, 0, 0.14); box-shadow: inset 3px 0 @yellow; } #workspaces button.drop-after { color: @yellow; background: rgba(255, 255, 0, 0.14); box-shadow: inset -3px 0 @yellow; }
    #clock, #battery, #cpu, #memory, #backlight, #disk, #network, #bluetooth, #pulseaudio, #wireplumber, #custom-media, #custom-notification-sound, #tray, #mode, #scratchpad, #power-profiles-daemon, #mpd, #language, #keyboard-state, #privacy-item { padding: 1.25px 12px; margin: 0; background: transparent; border: none; color: @teal; }
    #window, #workspaces { margin: 0 4px; } #custom-sep1, #custom-sep2, #custom-sep3, #custom-sep4, #custom-sep5, #custom-sep6, #custom-sep7 { color: @teal; opacity: 0.4; padding: 0 4px; margin: 0; }
    #custom-power { color: @red; padding: 1.25px 12px; margin: 0; } #custom-power:hover { color: @pink; text-shadow: 0 0 12.5px @pink; }
    #cpu { color: @teal; } #memory { color: @purple; } #disk { color: @orange; } #backlight { color: @yellow; } #battery, #battery.charging, #battery.plugged { color: @green; } #battery.critical:not(.charging), #network.disconnected, #bluetooth.off, #bluetooth.disabled, #wireplumber.muted, #mpd.disconnected, #temperature.critical { color: @red; } #battery.warning:not(.charging) { color: @orange; } #network, #bluetooth, #tray, #idle_inhibitor, #scratchpad { color: @teal; } #bluetooth.connected, #custom-media, #mpd, #idle_inhibitor.activated, #privacy-item.audio-in { color: @green; } #pulseaudio, #custom-notification-sound, #clock, #keyboard-state { color: @teal-light; } #pulseaudio.muted, #custom-notification-sound.muted, #mpd.stopped { color: @grey; } #wireplumber, #mode, #keyboard-state > label.locked, #tray > .needs-attention { color: @pink; } #mpd.paused { color: @gold; } #clock { font-weight: bold; letter-spacing: 1.25px; } #custom-weather { color: @blue; } #tray > .passive { opacity: 0.5; } #language { min-width: 16px; padding: 4px 8px; } #keyboard-state { padding: 4px 0px; min-width: 16px; } #scratchpad.empty { color: rgba(0, 255, 255, 0.3); } #mode { font-weight: bold; } #privacy { padding: 0; } #privacy-item.screenshare { color: @orange; } #privacy-item.audio-out { color: @teal; }
  '';

  light = ''
    @define-color teal #0077aa; @define-color teal-dim #006699; @define-color teal-light #0088bb; @define-color green #00aa55; @define-color pink #aa0088; @define-color red #cc0044; @define-color orange #cc5500; @define-color yellow #aa8800; @define-color purple #8800aa; @define-color blue #0088cc; @define-color grey #666666; @define-color gold #aa8800; @define-color black #ffffff; @define-color black-gradient #f5f5f5;
    * { font-family: 'JetBrainsMono Nerd Font', 'JetBrains Mono', 'Noto Sans Mono', 'Font Awesome 6 Free', 'Font Awesome 6 Brands', monospace; font-size: 16.25px; font-weight: 500; }
    window#waybar { background: linear-gradient(180deg, @black 0%, @black-gradient 100%); border-bottom: 2px solid @teal; box-shadow: 0 2.5px 10px rgba(0, 0, 0, 0.15); color: @teal; transition-property: background-color, border-color, box-shadow; transition-duration: 0.3s; border-radius: 0 0; }
    window#waybar.hidden { opacity: 0.2; } window#waybar.empty { background-color: transparent; } window#waybar.solo { background-color: @black; border: 2px solid @teal; }
    button { border: none; border-radius: 5px; background: rgba(0, 119, 170, 0.1); color: @teal; } button:hover { background: rgba(0, 119, 170, 0.2); box-shadow: 0 0 10px rgba(0, 119, 170, 0.3); }
    #workspaces button { padding: 5px 8px; margin: 0 4px; background: transparent; color: @teal-dim; border: none; } #workspaces button:hover { color: @teal; } #workspaces button.active { color: #B91C1C; font-weight: bold; } #workspaces button.urgent { color: @pink; } #workspaces button.dragging { opacity: 0.45; } #workspaces button.drop-before { color: @yellow; background: rgba(170, 136, 0, 0.14); box-shadow: inset 3px 0 @yellow; } #workspaces button.drop-after { color: @yellow; background: rgba(170, 136, 0, 0.14); box-shadow: inset -3px 0 @yellow; }
    #clock, #battery, #cpu, #memory, #backlight, #disk, #network, #bluetooth, #pulseaudio, #wireplumber, #custom-media, #custom-notification-sound, #tray, #mode, #scratchpad, #power-profiles-daemon, #mpd, #language, #keyboard-state, #privacy-item { padding: 1.25px 12px; margin: 0; background: transparent; border: none; color: @teal; }
    #window, #workspaces { margin: 0 4px; } #custom-sep1, #custom-sep2, #custom-sep3, #custom-sep4, #custom-sep5, #custom-sep6, #custom-sep7 { color: @teal; opacity: 0.4; padding: 0 4px; margin: 0; }
    #custom-power { color: @red; padding: 1.25px 12px; margin: 0; } #custom-power:hover { color: @pink; text-shadow: 0 0 10px @pink; }
    #cpu { color: @teal; } #memory { color: @purple; } #disk { color: @orange; } #backlight { color: @yellow; } #battery, #battery.charging, #battery.plugged { color: @green; } #battery.critical:not(.charging), #network.disconnected, #bluetooth.off, #bluetooth.disabled, #wireplumber.muted, #mpd.disconnected, #temperature.critical { color: @red; } #battery.warning:not(.charging) { color: @orange; } #network, #bluetooth, #tray, #idle_inhibitor, #scratchpad { color: @teal; } #bluetooth.connected, #custom-media, #mpd, #idle_inhibitor.activated, #privacy-item.audio-in { color: @green; } #pulseaudio, #custom-notification-sound, #clock, #keyboard-state { color: @teal-light; } #pulseaudio.muted, #custom-notification-sound.muted, #mpd.stopped { color: @grey; } #wireplumber, #mode, #keyboard-state > label.locked, #tray > .needs-attention { color: @pink; } #mpd.paused { color: @gold; } #clock { font-weight: bold; letter-spacing: 1.25px; } #custom-weather { color: @blue; } #tray > .passive { opacity: 0.5; } #language { min-width: 16px; padding: 4px 8px; } #keyboard-state { padding: 4px 0px; min-width: 16px; } #scratchpad.empty { color: rgba(0, 119, 170, 0.3); } #mode { font-weight: bold; } #privacy { padding: 0; } #privacy-item.screenshare { color: @orange; } #privacy-item.audio-out { color: @teal; }
  '';
}
