[global]
frame_color = #d8dee9

[urgency_low]
background = #d8dee9
foreground = #2e3440

[urgency_normal]
background = #e5e9f0
foreground = #2e3440

[urgency_critical]
background = #bf616a
foreground = #eceff4
